### ISSUE TITLE
stop disabling selinux

### ISSUE THREAD

**Issue by jduncan-rva** [ansible/lightbulb#102]
a horrible practice to show customers, especially in a scripted demo

**Comment by tima** [comment]
Spoke to @sdoran about this because I wasn't sure why that step was in there. The Lightbulb lessons used grafana. Getting grafana to work required letting it bind to a port that SELinux didn't allow and the `seport` module didn't work properly to resolve it. 

It's also worth mentioning that the lab provisioner was not designed to be used as a demo or how to build a production environment. 

Once we fully retire the v1 content along with the grafana lessons and workshops it won't serve a purpose and we'll remove it.

**Comment by tima** [comment]
Closed by the merge of PR #134.
