### ISSUE TITLE
add ansible vault to ansible essentials slide

### ISSUE THREAD

**Issue by jlozadad** [ansible/lightbulb#150]
is it possible to add ansible vault to the ansible essentials slide? was using this slide during a training session and was asked why it was it was not in the slides.

**Comment by tima** [comment]
This was intentional. There are a lot of things not in the decks because of time constraints and attempting to not overload students with too much information at one given time. `ansible-vault` serves a niche purpose (if you're using Tower or something like CyberArk there's no need for it) that it was deemed necessary for what the essentials deck is trying to do.

**Comment by rndmh3ro** [comment]
Is it possible to reopen this discussion?
From my perspective `ansible-vault` is essential and there are many more users that use vault than those who use tower.

Arguably its more often in use than the `block`-directive. So maybe add another "slide-down" to "Doing More with Playbooks", along templates, loops, blocks and so on?
