### ISSUE TITLE
Ran a workshop, multiple issues encountered. Will be submitting PRs

### ISSUE THREAD

**Issue by alberttwong** [ansible/lightbulb#190]
1. Had 40 attendees, didn't realize that AWS puts limits on ec2 instances.   Need readme to make sure that instructors request a higher ec2 limit.

2. We had bring your own computer.  Workshop didn't make it clear that people need to be running osx or linux. Some people came to class with windows machines.  Maybe an email or prereqs for class to be updated.

3. Since people brought their own computers, we had multiple issues.   The slide that says ansible is easy to install.....  did not happen.  We had people who had older python, SSH host checking not turned off, etc etc.    It's better to have them test ansible installed before coming to the workshop or point people to http://docs.ansible.com/ansible/latest/intro_installation.html.   That single slide was NOT helpful. 

4. People confused with architecture.  Need to add a slide before executing cli example.

**Comment by tima** [comment]
@alberttwong 

Your comments are generally out of scope for lightbulb here. Lightbulb provides content. Execution is a separate matter. I'd suggest you work more closely with the team that helped you run your workshop to learn how to better execute for the next time. 

1) This is why we recommend keeping workshops to around 25 students. Any more becomes problematic to execute including the AWS issue you ran into. 

2 & 3) We don't support that model and highly recommend never attempting to execute a bring your own computer workshop especially at scale. (I hope to get a self-paced learning edition for individuals using Vagrant at some point, but we aren't there yet.) Having personally done Ansible training before joining Red Hat I can tell you from experience that figuring out ~25 different environments at a workshop has an extremely high level of difficultly and is prone to failure. This is why we introduced the lab provisioner -- to streamline getting a room full of people on the same page quickly and efficiently in order to get down to the business of teaching the topic at hand. 

4) That comment is too vague to be sure what you are referring to. There are several slides where Ansible's architecture should be discussed with the "How Ansible Works" slide in the Essentials deck.
