### ISSUE TITLE
Control should default to rhel7-tower not rhel7

### ISSUE THREAD

**Issue by gdykeman** [ansible/lightbulb#98]
lightbulb/aws_lab_setup/roles/manage_ec2_instances/defaults/main.yml

Should be:
ec2_lab_node_types:
  - name: control
    type: rhel7-tower

Currently set to:
ec2_lab_node_types:
  - name: control
    type: rhel7

Which uses a t2.micro instance

**Comment by tima** [comment]
@gdykeman: Switching to rhel7-tower would cause the provisioner to spin up an instance with Tower pre-installed. Someone stepping lightbulb training may not want that and may not be interested in the Tower material. Also t2.micro is not enough machine to run Tower. With all of that in mind, I think defaulting to the most generic thing is the way to go.

**Comment by samdoran** [comment]
@gdykeman So you're effectively requested by the control node have Ansible Tower installed by default rather than an empty node?

That default stems from our old training curriculum where we had students install Ansible Tower. Fewer and fewer folks seem interested in that these days so I understand the desire for a change of the default. 

One thing to note: it _actually_ spins up the AMI with CentOS. I'm not sure there actually exists an AMI with Tower + RHEL. But that may not matter too much. Just an FYI.

**Comment by samdoran** [comment]
Just took a closer look at this and either Tower instance is defined as t2.medium, so node size is set properly.

The bigger issue is the "should" here. As @tima points out, someone may not want a Tower instance. The better route would be adding the ability to specify a lab environment, or specifying your own lab config until I get that feature a bit more baked.

**Comment by samdoran** [comment]
One slight issue I'm having is the login name for RHEL vs CentOS vs Ubuntu is different. Our current method of handling that isn't done completely since it sets one global value rather than a per instance value. This needs to be addressed in the provisioning role as well as the generated inventory files.

Nothing is ever simple.

**Comment by samdoran** [comment]
I solved the login name issue in 053bb7d258db243235dbbe97dc84c85ef15444db.

Still seems the best way to override the default lab config is via the extra-vars used during provisioning.
